title: Toe's blog
description: what I'm playing with | let's build AI for the people
lang: en
url: https://zjutoe.github.io
baseurl: ""
giscus:
  enabled: true
  repo: zjutoe/zjutoe.github.io
  repo_id: R_kgDOUSX2GQ
  category: Announcements
  category_id: DIC_kwDOUSX2Gc4DGNLF
permalink: /posts/:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - README.md
